version: "3.2"

services:
  postgres:
    image: postgres:latest
    container_name: referral-db
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-referral}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  app:
    build: .
    container_name: referral-app
    environment:
      POSTGRES_URL: ${POSTGRES_URL:-postgres://user:password@db:5432/referral}
      PUBLIC_PORT: ${PUBLIC_PORT:-3000}
      PRIVATE_PORT: ${PRIVATE_PORT:-3001}
      ROOT_ISSUER: ${ROOT_ISSUER:-did:key:z6MkehxGCJwrg8DmqzjgUxZ8np2e3FVUJkzNGneEoXicrQyZ}
      RPC_URL: ${RPC_URL:-http://localhost:8545}
      CHAIN_ID: ${CHAIN_ID:-10}
      DOMAIN_NAME: ${DOMAIN_NAME:-https:/geoweb.network}
    ports:
      - "${PUBLIC_PORT:-3000}:${PUBLIC_PORT:-3000}"
      - "${PRIVATE_PORT:-3001}:${PRIVATE_PORT:-3001}"

volumes:
  data: {}