version: "3.2"

services:
  postgres:
    image: postgres:latest
    container_name: referral-db
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-referral}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  app:
    build: .
    container_name: referral-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-referral}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      PUBLIC_PORT: ${PUBLIC_PORT:-3000}
      PRIVATE_PORT: ${PRIVATE_PORT:-3001}
    ports:
      - "${PUBLIC_PORT:-3000}:${PUBLIC_PORT:-3000}"
      - "${PRIVATE_PORT:-3001}:${PRIVATE_PORT:-3001}"

volumes:
  data: {}